// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using instructor.Data;

#nullable disable

namespace instructor.Migrations
{
    [DbContext(typeof(InstructorTestContext))]
    [Migration("20220406203121_initial_migration")]
    partial class initial_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("instructor.Models.Instructor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grades")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Instructor");
                });
#pragma warning restore 612, 618
        }
    }
}
